export enum HTTP_STATUS {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    NON_AUTHORITATIVE_INFORMATION = 203,
    NO_CONTENT = 204,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500,
    UNPROCESSABLE_ENTITY = 422,
    CONFLICT = 409,
};

export enum ErrorCodes {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    UNAUTHORIZED = 'UNAUTHORIZED',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    TOKEN_MISSING = 'TOKEN_MISSING',
    TOKEN_INVALID = 'TOKEN_INVALID',
    INVALID_FILE = 'INVALID_FILE',
    INVALID_PARAMETERS = 'INVALID_PARAMETERS',
    AT_LEAST_ONE_IMAGE_REQUIRED = 'AT_LEAST_ONE_IMAGE_REQUIRED',
    FORBIDDEN = 'FORBIDDEN',
}